# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---
# Common platform setup playbook
- hosts: controller_group
  any_errors_fatal: true

  pre_tasks:
    - name: set node name
      set_fact: node_name={{ ansible_nodename | lower }}
    - name: check deployment settings
      include_tasks: ./tasks/settings_check_ne.yml
    - name: print deployment settings
      include_tasks: ./tasks/print_vars.yml

  roles:
    - role: machine_setup/os_setup
    - role: time/ntp
      when: ntp_enable | default(False)
    - role: git_repo
    - role: golang
    - role: docker

# Playbook for emco cluster deployment
- hosts: controller_group
  roles:
    - role: kubernetes/controlplane
    - role: kubernetes/
    - role: kubernetes/helm
    - role: harbor_registry/controlplane
    - role: kubernetes/cni
    - role: emco/controlplane
