# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2021 Intel Corporation

---

# Common platform setup playbook
- hosts: edgenode_group:controller_group
  any_errors_fatal: true

  pre_tasks:
    - name: set node name
      set_fact: node_name={{ ansible_nodename | lower }}
    - name: create helper variable
      set_fact:
        single_node_deployment: false
    - name: check deployment settings
      include_tasks: "{{ playbook_dir }}/tasks/settings_check_ne.yml"
    - name: print deployment settings
      include_tasks: "{{ playbook_dir }}/tasks/print_vars.yml"

- name: Provision offline installation package
  import_playbook: playbooks/offline_package.yml
  when: offline_enable | default(False)

- name: Provision target infrastructure
  import_playbook: playbooks/infrastructure.yml

- name: Provision Kubernetes cluster
  import_playbook: playbooks/kubernetes.yml

- name: Provision Applications
  import_playbook: playbooks/applications.yml

# Play for edge nodes that have VCAC-A card installed
- hosts: edgenode_vca_group
  any_errors_fatal: true

  pre_tasks:
    - name: set node name
      set_fact: node_name={{ ansible_nodename | lower }}
    - name: check deployment settings
      include_tasks: ./tasks/settings_check_ne.yml
    - name: print deployment settings
      include_tasks: ./tasks/print_vars.yml

  roles:
    - role: infrastructure/os_setup
    - role: infrastructure/time_setup_ntp
      when: ntp_enable | default(False)
    - role: infrastructure/time_verify_ntp
    - role: infrastructure/git_repo
    - role: infrastructure/golang
    - role: infrastructure/docker
    - role: infrastructure/vca_host_setup
    - role: infrastructure/conditional_reboot
    - role: infrastructure/vca_node_setup
    - role: kubernetes/node
    - role: kubernetes/harbor_registry/node
    - role: kubernetes/cni
    - role: telemetry/collectd/node
    - role: telemetry/cadvisor/node
    - role: applications/openness/node
    - role: telemetry/pcm/node
      when: telemetry_pcm_enable | default(False)
    - role: kubernetes/hddl/vca_setup
