# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

# Playbook for On-Premises deployment

- hosts: controller_group
  vars:
    hugepage_amount: "1024" # only applicable for ovncni deployment

  pre_tasks:
  - debug:
      msg: "Setting up {{ inventory_hostname }} at {{ ansible_host }}"
  - name: Check if only one controller is enabled
    fail:
      msg: "Only one controller is supported"
    when:
    - groups['controller_group'] is defined
    - (groups['controller_group']|length>1)
  - name: Hostname precheck
    include_tasks: ./tasks/precheck_hostname.yml

  roles:
    - role: offline/restore/transfer
      when: offline_mode
    - role: offline/restore/yum/setup
      when: offline_mode
    - role: machine_setup/os_setup
    # - role: time/ntp
    - role: docker
    - role: git_repo
    - role: golang
    - role: openness/onprem/master
    - role: cnca/onprem
    - role: nfd/onprem/master
    - role: offline/restore/ngc_test
      when: offline_mode and epcforedge_git_repo is defined
    #- role: ngc_test/onprem/master
    - role: apache
    - role: offline/restore/yum/clean
      when: offline_mode


- hosts: edgenode_group
  pre_tasks:
  - debug:
      msg: "Setting up {{ inventory_hostname }} at {{ ansible_host }}"
  - include_tasks: ./tasks/precheck_hostname.yml
  # - include_tasks: ./roles/hddl/common/tasks/precheck.yml

  roles:
    - role: offline/restore/transfer
      when: offline_mode
    - role: offline/restore/yum/setup
      when: offline_mode
    - role: machine_setup/os_setup
    # - role: time/ntp
    - role: time/verify

    - role: machine_setup/custom_kernel
    - role: machine_setup/grub
    - role: machine_setup/configure_tuned
    - role: machine_setup/conditional_reboot

    - role: dpdk
    - role: golang
    - role: docker
    - role: libvirt
    - role: qemu
    - role: sriov_device_init/onprem
    - role: git_repo
    # - role: ovs
    - role: openness/onprem/worker
    # - role: hddl/onprem/worker
    - role: nfd/onprem/worker
    - role: offline/restore/yum/clean
      when: offline_mode
