# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- hosts: controller_group:edgenode_group
  any_errors_fatal: true

  tasks:
    - block:
        - name: include readiness tasks
          include: ./tasks/readiness_tasks.yml
      rescue:
        - block:
          - name: Call log collector
            include_tasks: ./tasks/collect_logs.yml
            when:
              - collect_logs_after_failure | default(True)
          - name: propagate failure with logs
            fail:
              msg: |
                Issues were found. Check logs of this playbook's execution for the reason.
                "Gathered logs are in the archive: {{ log_filename }}"
            when:
              - collect_logs_after_failure | default(True)

          - name: propagate failure without logs
            fail:
              msg: |
                Issues were found. No logs collected because collect_logs_after_failure is set to False.
            when:
              - not collect_logs_after_failure | default(False)
          tags: always

