# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation
---

- name: remove BB config release if exist
  block:
  - name: check if release exists
    command: helm status intel-bb-cfg-fpga
    ignore_errors: yes
    register: get_release_bb_cfg
  - name: remove BB config release
    command: helm uninstall intel-bb-cfg-fpga
    when: get_release_bb_cfg.rc == 0
    changed_when: true

- name: remove BB config helm charts
  file:
    name: "{{ item }}"
    state: absent
  with_items:
  - "{{ ne_helm_charts_default_dir }}/bb_config"
