# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---
- name: install EPEL package
  yum:
    name: epel-release
    state: present
  become: yes
  when: 
    - not offline_enable
    - ansible_distribution == "CentOS"
