# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

FROM debian:stretch

ARG BUNDLE_DIR

# Porter does not support default docker proxy for building and it has to be added manually to this file
# ENV https_proxy=http://proxy-example.com:123
# ENV http_proxy=http://proxy-example.com:123
# ENV no_proxy=localhost,127.0.0.1

RUN apt-get update && apt-get install -y ca-certificates git python3-pip jq
RUN pip3 install ansible netaddr

# This is a template Dockerfile for the bundle's invocation image
# You can customize it to use different base images, install tools and copy configuration files.
#
# Porter will use it as a template and append lines to it for the mixins
# and to set the CMD appropriately for the CNAB specification.
#
# Add the following line to porter.yaml to instruct Porter to use this template
# dockerfile: Dockerfile.tmpl

# You can control where the mixin's Dockerfile lines are inserted into this file by moving "# PORTER_MIXINS" line
# another location in this file. If you remove that line, the mixins generated content is appended to this file.
# PORTER_MIXINS

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR
