# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

_kubernetes_env_file: "{{ '/etc/sysconfig/kubelet' if ansible_distribution == 'CentOS' else '/etc/default/kubelet' }}"
_kubernetes_config_file: "/usr/lib/systemd/system/kubelet.service.d/kubelet_config.yml"

cpu:
  policy: "static" # Options: none (disabled), static (default)
  reserved_cpus: 1

topology_manager:
  policy: "best-effort" # Options: none (disabled), best-effort (default), restricted, single-numa-node
